update for public

diff --git a/xbkapi b/xbkapi
--- a/xbkapi
+++ b/xbkapi
@@ -11,66 +11,66 @@
 # http://docs.bkapigw.oa.com/guide/apigateway/use-api/bk-app.html
 # _create_access_token pin+token dezhaoli ******
 # _create_access_token outlook dezhaoli ******
-# _create_access_token cookie dezhaoli 4jpKfRdutY8Jzq7cN3hRljkOta0snzg7HBXKyYfglcY
+# _create_access_token cookie dezhaoli 4jpKfRdutY8Jzq7cN3hRljkOta0snzg7HBXKy******
 # _create_access_token app
 #@
 function create-access-token()
 {
-  mode="$1"
-  shift
-  if [[ "$mode" == "outlook" ]]; then
-    username=$1
-    password=$2
-    args="-d grant_type=authorization_code -d id_provider=tof_ldap -d username=$username -d password=$password"
-  elif [[ "$mode" == "pin+token" ]]; then
-    username=$1
-    password=$2
-    args="-d grant_type=authorization_code -d id_provider=tof_token -d username=$username -d password=$password"
-
-  elif [[ "$mode" == "cookie" ]]; then
-    bk_uid=$1
-    bk_ticket=$2
-    args="-d grant_type=authorization_code -d rtx=$bk_uid -d bk_ticket=$bk_ticket"
-  elif [[ "$mode" == "app" ]]; then
-    args="-d grant_type=client_credentials"
-  else
-    echo 'Failed to create access_token. no mode match' 1>&2
-    exit 1
-  fi
+    local mode=                         #@ choices=( outlook pin+token cookie app )
+    local app_code=                     #@ --app-code;
+    local app_secret=                   #@ --app-secret;
+    local username=                     #@ --username;
+    local password=                     #@ --password;
+    ____ "$@"
   
-  api_url='http://apigw.o.oa.com/auth_api/token/'
-  result=$(curl -s "$api_url" \
-            -d "app_code=$APP_CODE" \
-            -d "app_secret=$APP_SECRET" \
-            -d "env_name=$l_env_type" \
-            $args )
-  access_token="$(echo "$result" | jq -r .data.access_token)"
+    local args;
+    if [[ "$mode" == "outlook" ]]; then
+        args="-d grant_type=authorization_code -d id_provider=tof_ldap -d username=$username -d password=$password"
+    elif [[ "$mode" == "pin+token" ]]; then
+        args="-d grant_type=authorization_code -d id_provider=tof_token -d username=$username -d password=$password"
+    elif [[ "$mode" == "cookie" ]]; then
+        args="-d grant_type=authorization_code -d rtx=$username -d bk_ticket=$password"
+    elif [[ "$mode" == "app" ]]; then
+        args="-d grant_type=client_credentials"
+    else
+        echo 'Failed to create access_token. no mode match' 1>&2
+        exit 1
+    fi
 
-  if [[ -z "$access_token" || "$access_token" == "null" ]]; then
-    echo 'Failed to create access_token' 1>&2
-    exit 1
-  fi
-  echo $access_token
+    local api_url='http://apigw.o.oa.com/auth_api/token/'
+    local result=$(curl -s "$api_url"                   \
+                        -d "app_code=$app_code"         \
+                        -d "app_secret=$app_secret"     \
+                        -d "env_name=$l_env_type"       \
+                        $args )
+    local access_token="$(echo "$result" | jq -r .data.access_token)"
+
+    if [[ -z "$access_token" || "$access_token" == "null" ]]; then
+        die 'Failed to create access_token'
+    fi
+    echo $access_token
 }
 
 
 #@
 function refresh-access_token()
 {
+    local token=                     #@
+    local app_code=                  #@ --app-code;
+    ____ "$@"
 
-    api_url='http://apigw.o.oa.com/auth_api/refresh_token/'
-    refresh_token="$1"
-    result=$(curl -G -s "$api_url" \
-            -d "app_code=$APP_CODE" \
-            -d "refresh_token=$refresh_token" \
-            -d "env_name=$l_env_type" \
-            -d "grant_type=refresh_token" \
-            $args )
-    access_token="$(echo "$result" | jq -r .data.access_token)"
+    local args;
+    local api_url='http://apigw.o.oa.com/auth_api/refresh_token/'
+    local result=$(curl -G -s "$api_url"                \
+                        -d "app_code=$app_code"         \
+                        -d "refresh_token=$token"       \
+                        -d "env_name=$l_env_type"       \
+                        -d "grant_type=refresh_token"   \
+                        $args )
+    local access_token="$(echo "$result" | jq -r .data.access_token)"
 
     if [[ -z "$access_token" || "$access_token" == "null" ]]; then
-    echo 'Failed to refresh access_token' 1>&2
-    exit 1
+        die 'Failed to refresh access_token'
     fi
     echo $access_token
 }
@@ -81,7 +81,7 @@ function artifactory-search()
     local file_name=                 #@
     ____ "$@"
 
-    api_url="https://bkrepo.woa.com/web/repository/api/node/search"
+    local api_url="https://bkrepo.woa.com/web/repository/api/node/search"
 
     if [[ "$l_artifactory_type" == PIPELINE ]]; then
         local repo_name=pipeline
@@ -102,12 +102,12 @@ function artifactory-search()
 
 EOF
 
-    result=$(curl -s -X POST \
-    -H "Content-Type: application/json" \
-    -H "Accept:application/json" \
-    -d "$post_data" \
-    --cookie " bk_ticket=${l_bk_ticket};  " \
-    "$api_url" )
+    local result=$(curl -s -X POST                              \
+                        -H "Content-Type: application/json"     \
+                        -H "Accept:application/json"            \
+                        -d "$post_data"                         \
+                        --cookie " bk_ticket=${l_bk_ticket};  " \
+                        "$api_url" )
 
 
     echo "$result"
@@ -118,17 +118,16 @@ EOF
 #@
 function get-artifactory-list()
 {
-
     local pipelineId=                 #@
     local buildId=                    #@
     ____ "$@"
   
-    api_url="http://devops.apigw.o.oa.com/${l_env_type}/v2/apigw-user/artifactories/projects/${l_project_id}"
+    local api_url="http://devops.apigw.o.oa.com/${l_env_type}/v2/apigw-user/artifactories/projects/${l_project_id}"
     api_url="${api_url}/pipelines/${pipelineId}/builds/${buildId}/search"
-    result=$(curl -s -i -X GET "" \
-    -H "Accept:application/json" \
-    -H "Content-Type:application/json" \
-    "$api_url?access_token=${l_access_token}" | sed '1,16d')
+    local result=$(curl -s -i -X GET ""                         \
+                        -H "Accept:application/json"            \
+                        -H "Content-Type:application/json"      \
+                        "$api_url?access_token=${l_access_token}" | sed '1,16d')
 
     echo "$result"
 
@@ -141,17 +140,16 @@ function get-download-url()
     local path=                       #@
     ____ "$@"
 
-    api_url="http://devops.apigw.o.oa.com/${l_env_type}/v2/apigw-user/artifactories/projects/${l_project_id}"
+    local api_url="http://devops.apigw.o.oa.com/${l_env_type}/v2/apigw-user/artifactories/projects/${l_project_id}"
     api_url="${api_url}/thirdPartyDownloadUrl"
-    result=$(curl -s -i -X GET "" \
-    -H "Accept:application/json" \
-    -H "Content-Type:application/json" \
-    "$api_url?path=${path}&amp;artifactoryType=${l_artifactory_type}&amp;access_token=${l_access_token}" )
+    local result=$(curl -s -i -X GET ""                         \
+                        -H "Accept:application/json"            \
+                        -H "Content-Type:application/json"      \
+                        "$api_url?path=${path}&amp;artifactoryType=${l_artifactory_type}&amp;access_token=${l_access_token}" )
 
-    download_url="$(echo "$result" | sed -n '/{/,$p' | jq -r .data[0])"
+    local download_url="$(echo "$result" | sed -n '/{/,$p' | jq -r .data[0])"
     if [[ -z "$download_url" || "$download_url" == "null" ]]; then
-        echo 'Failed to get download_url' 1>&2
-        exit 1
+        die 'Failed to get download_url'
     fi
     echo $download_url
 }
@@ -162,21 +160,23 @@ function get-download-url()
 #@ 
 function get-build-variables-value()
 {
-    local pipelineId=                 #@
-    local buildId=                    #@
-    local keys=                       #@
+    local pid=                          #@
+    local uid=                          #@
+    local keys=                         #@
     ____ "$@"
 
     api_url="https://devops.apigw.o.woa.com/${l_env_type}/v3/apigw-user/projects/${l_project_id}"
-    api_url="${api_url}/pipelines/${pipelineId}/builds/${buildId}/variables"
-    result=$(curl -s -X POST \
-    -H "X-Bkapi-Authorization: {\"access_token\": \"${l_access_token}\"}" \
-    -H "Content-Type: application/json" \
-    -d "[ 
-            $keys 
-     ]" \
-    -H "Accept:application/json" \
-    "$api_url" )
+    api_url="${api_url}/pipelines/${pid}/builds/${uid}/variables"
+    result=$(curl -s -X POST                                                                \
+                    -H "X-Bkapi-Authorization: {\"access_token\": \"${l_access_token}\"}"   \
+                    -H "Content-Type: application/json"                                     \
+                    -d "[ $keys ]"                                                          \
+                    -H "Accept:application/json"                                            \
+                    "$api_url" )
+
+
+    local result_result=$(echo "$result" | jq -r '.result')
+    [[ "$result_result" == "true" ]] || die "Failed to get build variables: $result"
 
     echo "$result"
 }
@@ -192,8 +192,6 @@ function main-ex()
     l_bk_ticket=                                                      #@ --ticket; help='set bk_ticket'
     ____ "$@"
 
-    APP_CODE=oadezhaoli
-    APP_SECRET=JHtgRaZ5oXFb7DrZqbyT5Y4r5da63mWVleTkFwYcKdHvc7BlHo
 
 }
 
